namespace: pan-finder

resources:
  - ../../base
  - frontend-deployment.yaml
  - frontend-service.yaml
  - pv.yaml

patches:  
  - path: ingress-patch.yaml
  - path: configmap-patch.yaml
  - path: pgvector-deployment-patch.yaml
  - path: pvc-patch.yaml

images:
  - name: ghcr.io/pan-finder/pan-finder-server
    newName: ghcr.io/pan-finder/pan-finder-server
    newTag: v1.0.0-alpha.7
  - name: ghcr.io/pan-finder/pan-finder-frontend
    newName: ghcr.io/pan-finder/pan-finder-frontend
    newTag: v1.0.0-alpha.7
    
labels:
  - pairs:
      environment: dev
