apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgvector-data-pv
  labels:
    app.kubernetes.io/name: pgvector
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: pan-finder
    environment: dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/k8s-pods/data/pan-finder-postgresql
    server: swapnfs.ess.eu
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  volumeMode: Filesystem