name: pan-finder
services:
  pgvector:
    build:
      context: database
      dockerfile: Dockerfile.postgresql
    ports:
      - 5432:5432
    volumes:
      - ./pgvector/data:/var/lib/postgresql/data # for persisting data
      - ./pgvector/init:/docker-entrypoint-initdb.d # for initializing db
      - ./database/backup:/backup # for easy backup and restore
    environment:
      - POSTGRES_DB=pan-finder
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d pan-finder -U usr" ]

  server:
    build:
      context: ./server
      dockerfile: docker/Dockerfile.dev
    container_name: pan-finder-server
    command: python debug_server.py
    ports:
      - 8080:8080
      - 5678:5678 # Debug port
    hostname: server
    volumes:
      - ./server:/code/app
      - ./models:/code/models
    working_dir: /code/app
    env_file:
      - ./server/.env.dev
    environment:
      - PYTHONPATH=/code/app
      - DEBUG_PORT=5678
      - DEBUG_WAIT=false
      - API_PORT=8080
    depends_on:
      pgvector:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    container_name: pan-finder-frontend
    hostname: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app # for hot reloading
      - /app/node_modules # for caching
    command: npm run start
    env_file:
      - ./frontend/.env.dev
    depends_on:
      - server
