apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pan-finder-ingress
spec:
  ingressClassName: traefik-proxy-prod
  tls:
  - hosts:    
    - pan-finder.ess.eu
    secretName: pan-finder-tls
  rules:
  - host: pan-finder.ess.eu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pan-finder-server-service
            port:
              number: 8080
