apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvector
spec:
  template:    
    spec:
      imagePullSecrets:
      - name: ess-gitlab-registry-credentials
      containers:
      - name: pgvector
        args:
          - postgres
          - -c
          - logging_collector=off
          - -c
          - log_destination=stderr
          - -c
          - log_min_duration_statement=1000
          - -c
          - log_statement=mod
          - -c
          - log_duration=off
          - -c
          - shared_buffers=512MB
          - -c
          - work_mem=64MB
          - -c
          - maintenance_work_mem=256MB
          - -c
          - effective_cache_size=2GB
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
      - name: shared-memory
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi