apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pan-finder-secrets
spec:
  vaultAuthRef: pan-finder-auth
  mount: static
  type: kv-v2
  path: /v1/static/data/SIMS/pan-finder/prod
  refreshAfter: 60s
  destination:
    create: true
    name: pan-finder-secrets
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ess-gitlab-registry-credentials
spec:
  vaultAuthRef: pan-finder-auth
  mount: static
  type: kv-v2
  path: /v1/static/data/SIMS/pan-finder/prod/docker-registry
  refreshAfter: 60s
  destination:
    create: true
    name: ess-gitlab-registry-credentials
    type: kubernetes.io/dockerconfigjson

