apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgvector-data
  namespace: pan-finder
  labels:
    app.kubernetes.io/name: pgvector
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage
