namespace: pan-finder-dev

resources:
  - ../../base
  - frontend-deployment.yaml
  - frontend-service.yaml

patchesStrategicMerge:
  - server-deployment-patch.yaml
  - pvc-patch.yaml
  - ingress-patch.yaml

commonLabels:
  environment: dev

configMapGenerator:
  - name: server-config
    behavior: merge
    literals:
      - ALLOWED_ORIGINS=https://pan-finder.dev-sims.ess.eu
