namespace: pan-finder-dev

resources:
  - ../../base
  - frontend-deployment.yaml
  - frontend-service.yaml

patches:
  - path: server-deployment-patch.yaml
  - path: ingress-patch.yaml
  - path: configmap-patch.yaml

labels:
  - pairs:
      environment: dev
