namespace: pan-finder-dev

resources:
  - ../../base
  - frontend-deployment.yaml
  - frontend-service.yaml

patches:
  - path: ingress-patch.yaml
  - path: configmap-patch.yaml

images:
  - name: ghcr.io/pan-finder/pan-finder-server
    newName: ghcr.io/pan-finder/pan-finder-server
    newTag: dev
  - name: ghcr.io/pan-finder/pan-finder-frontend
    newName: ghcr.io/pan-finder/pan-finder-frontend
    newTag: dev

labels:
  - pairs:
      environment: dev
